### ISSUE TITLE
Confusing output for "cm use cc <claim>"

### ISSUE THREAD

**Issue by KevinFCormier** [open-cluster-management/cm-cli#70]
The bolded text in this output is confusing because it suggests the context should now be clusterpoolhost/console-squad/api.collective.aws.red-chesterfield.com/console, but in fact when the command finishes, it is **daily**

% cm use cc daily
**Switching to context clusterpoolhost/console-squad/api.collective.aws.red-chesterfield.com/console**
clusterclaim daily is running with id console-aws-47-dpp8q (1/60)
kcormier@snugbug bin % oc config current-context
daily

**Comment by itdove** [comment]
@knrc in fact it is because we have to switch to the console context to grab the secret in order to create the SA on the cc cluster. What we can do is add a second switching message after to show the last context or totally remove that message.
What do you prefer?

**Comment by KevinFCormier** [comment]
Are you actually changing the current context for the user? For cluster-keeper, when it needs to use the ClusterPool host context, it uses the `--context` option on `oc` so that it's only used for those commands. So I would only display the current message if it is actually changing the user's context, but preferably it shouldn't. If it isn't, then I think it's an internal detail that is probably not interesting to the user, and it would be more accurate to say that you're _using_ a particular context, rather than switching to it, if you want to display some output to confirm that.

I do think it would be helpful to add the second message to tell the user which context is now active, just like `oc` would do:
```
% oc config use-context daily
Switched to context "daily".
```

**Comment by itdove** [comment]
yes you are correct, I shouldn't touch the kubeconfig context but instead when I create the client, use the correct context and not the current one... 
It will need a number of refactoring and test in order to fix that.

**Comment by itdove** [comment]
hmmm, it seems that switch is not needed as I already use the cph context to create the client.... 
I will investigate further
